defaults:
  - models: xgboost
  - datasets: iris
  - override hydra/job_logging: custom
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - _self_

save_plot: True
random_state: 42

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: logreg
    storage: null
    n_trials: 20
    n_jobs: 1

C: 1.0
penalty: l2



