defaults:
  - models: xgboost
  - datasets: iris
  - override hydra/job_logging: disabled
  - _self_

log_path: "log/"
log_level: 20
save_plot: True
console_log: True
random_state: 42

hydra:
  run:
    dir: "."